<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <RootNamespace />
  </PropertyGroup>

  <Import Project="..\uefi-cs\uefi-cs.projitems" Label="Shared" />

  <Import Project="..\NES\NES.projitems" Label="Shared" />
  
  <ItemGroup>
    <NativeLibrary Include="..\x64\Debug\NativeLib.lib" />
    <NativeLibrary Include="..\x64\Debug\doomgeneric.lib" />
    <NativeLibrary Include="..\x64\Debug\quakegeneric.lib" />
  </ItemGroup>

</Project>
